### PR TITLE
WIP PSR7 conformance tests

### PR DESCRIPTION
**Pull request by Maks3w**
This is an example of integration with [maks3w/psr7-assertions](https://github.com/Maks3w/Psr7Assertions) a PSR-7 conformance test library

This library aims to provide a common set of tests for every PSR-7 implementation

### CODE REVIEW

**Comment by weierophinney** [comment]
@Maks3w I've pushed fixes to issues to https://github.com/weierophinney/zend-diactoros/tree/hotfix/49

However, there's one test I disagree with: `PHPUnit\ResponseInterfaceTestsTrait::testValidDefaultReasonPhrase`. It assumes that if no reason phrase was provided, that an empty string **must** be returned. This is not true. The docblock explicitly says that implementations:

> MAY choose to return the default RFC 7231 recommended reason phrase (or those listed in the IANA HTTP Status Code Registry) for the response's status code.

which is exactly what Diactoros does.

Once you fix that test, I think I can merge the changes both you and I have done.

**Comment by samsonasik** [comment]
need rebase

**Comment by Maks3w** [comment]
@samsonasik A better review was "don't use dev-master versions please tag a stable one" and even better "I won't review WIP PRs"

**Comment by samsonasik** [comment]
sorry, but that's just a reminder "in case"...

Warm regards,

Abdul Malik Ikhsan

Pada 13 Jun 2015, pukul 15.57, Maks3w <notifications@github.com> menulis:

**Comment by Maks3w** [comment]
@samsonasik Take note that a WIP PR is not intended to be merged by the PR author. So It's expected while still be a WIP the PR may fail and may present conflict.

**Comment by GeeH** [comment]
There's no need to be a dick about it @Maks3w.

**Comment by weierophinney** [comment]
I've deleted several comments on this thread, as the behavior and communication were not civil or advancing the discussion of this pull request.

**Comment by Maks3w** [comment]
This PR is not intended to be merged. This PR only present the Prs7Assertions project for to discuss about if the implementation is or not correct.

**Comment by weierophinney** [comment]
> This PR only presents the Prs7Assertions project for to discuss about if the implementation is or not correct.

@Maks3w Okay. That said, please see my note above: one of the assertions is incorrect currently. Implementations are allowed to cast a reason phrase to the IANA recommended reason phrase if one exists. If you truly want to check against an empty-string reason phrase, you'll need to set the status to one that isn't currently defined by the IANA.

**Comment by weierophinney** [comment]
@Maks3w Also, while you may not intend to merge it, I fixed items as a result of merging locally. As such, I'd really love to have this mergeable at some point...

**Comment by weierophinney** [comment]
I've cherry-picked the code changes, and updated the two tests in `RequestTest` that needed changes to properly reflect the spec.

**Comment by weierophinney** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
