### PR TITLE
[] short array syntax

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by gianarb** [comment]
:+1:

**Comment by weierophinney** [comment]
I can't believe a missed some! Thanks, @samsonasik !

**Comment by samsonasik** [comment]
you're welcome. should I make PRs to other zf components about it or wait until 2.5 and target to their develop branch?

Warm regards,

Abdul Malik Ikhsan

Pada 28 Mei 2015, pukul 00.43, weierophinney <notifications@github.com> menulis:

**Comment by Maks3w** [comment]
@samsonasik Please don't send PRs against the rest of components.

**Comment by samsonasik** [comment]
ok

Warm regards,

Abdul Malik Ikhsan

Pada 28 Mei 2015, pukul 14.42, Maks3w <notifications@github.com> menulis:

**Comment by Maks3w** [comment]
#38 Automatize this check. Supersede this PR

**Pull request closed without merging**
