### PR TITLE
Added stream rewind in JsonResponse constructor

### PR DESCRIPTION
**Pull request by NikolaySl**

### CODE REVIEW

**Comment by weierophinney** [comment]
Thanks for reporting this and providing a patch! I was about to merge, and realized the issue was also present in the HTML and text response types! I'm updating those as part of the merge.

**Comment by NikolaySl** [comment]
Thanks for very fast fixes. 

When new version will be released?

**Comment by weierophinney** [comment]
@NikolaySl Already done; 1.3.1 has the fixes.

**Comment by mnapoli** [comment]
@weierophinney how are we supposed to write to the stream afterwards since it has been rewinded?

Let's say we have a middleware that adds additional content to the stream, `$response->getBody()->write()` will overwrite existing data in the stream?

**Comment by mnapoli** [comment]
Moved my question to #195, it affects all response classes.

**Pull request merged**
