### PR TITLE
Added vendor to travis cache

### PR DESCRIPTION
**Pull request by weierophinney**
- Per http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/

Mainly testing this out. :)

### CODE REVIEW

**Comment by weierophinney** [comment]
You can see the differences between the two builds:

- https://travis-ci.org/zendframework/zend-diactoros/builds/73249995
- https://travis-ci.org/zendframework/zend-diactoros/builds/73250365

HHVM does not benefit much from the change, but the other builds take around 50% less time overall, and the full time for all jobs dropped by a > 30%. Definitely worth it!

**Comment by Maks3w** [comment]
1. We need a way of print what depenency versions are used. At this moment we are blind on that.
2. Take this other comparison
https://travis-ci.org/zendframework/zend-diactoros/builds/70634633
https://travis-ci.org/zendframework/zend-diactoros/builds/73250365

It's not fair to evaluate a cold cache 

I suggest to fix 1 and don't propagate this across the whole repos until we can verify how works when new versions are released

**Comment by weierophinney** [comment]
@Maks3w (1) can be fixed as easily as adding this as a `before_script`:

```yaml
- composer info -i
```

Regarding (2), I honestly don't understand why the 1.1.2 release built so quickly; most of the other builds I've seen have been closer to the original build of this PR.

I'll get a PR in place with the `composer info -i` change.

**Comment by Maks3w** [comment]
Travis runs faster in the morning (Europe) night (America) because the anonymous rate limit against GitHub API is not so exhausted.

If Composer can install using dist version (not clone) then the dependency can be sucesfully saved in the cache

IMO we have a very good decent speed rate. I hope Composer will improve the work with Travis-CI cache without the need of this kind of workarounds

**Pull request merged**
