### PR TITLE
in-line representation

### PR DESCRIPTION
**Pull request by gianarb**
I'm expert of README.md file :)

ping @Ocramius

### CODE REVIEW

**Comment by Maks3w** [comment]
Please keep the same format as https://raw.githubusercontent.com/zendframework/zf2/master/README.md

**Comment by gianarb** [comment]
Fixed.. Can you think to use the same format in your PRs in other zf-components?
Thanks

**Comment by Ocramius** [comment]
Merged, thanks!

`master`: zendframework/zend-diactoros@8f8d3e2f5be97e92aa7caf262b2624db5e61521c
`develop`: zendframework/zend-diactoros@3450fc1ae5936347816324e8c625b1558d534d16

**Comment by Maks3w** [comment]
When develop branch exists README should updated

**Pull request merged**
