### PR TITLE
500 error with Apache

### PR DESCRIPTION
**Pull request by bluebaroncanada**
Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
Yes
  - [x] Detail how the bug is invoked currently.
Using Apache 2.4.29 making any request
  - [x] Detail the original, incorrect behavior.
Throws a 500 error: <address>Apache/2.4.29 (Ubuntu) Server at dev2.studentfleamarket.com Port 443</address> is not a valid header
  - [x] Detail the new, expected behavior.
Removes that header.
  - [x] Base your feature on the `master` branch, and submit against that branch.
Okay.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
Test already exists/not necessary
  - [x] Add a `CHANGELOG.md` entry for the fix.
Done

- [x] Is this related to quality assurance?
Probably not.  Related to #346.
More information in the blame for #344

### CODE REVIEW

**Comment by bluebaroncanada** [comment]
More on this issue is in the blame for #344

**Comment by Moln** [comment]
I have the same issue.

**Comment by malukenho** [comment]
I'm not sure if we should revert it or tag a new version from the old hash meanwhile we introduce a proper fix for it.

**Comment by bluebaroncanada** [comment]
I don't think it needs a fix.

**Comment by tptrixtop** [comment]
This fix cause an issue in apache on win, because there is a header
`
    [SERVER_SIGNATURE] =>
<address>Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.9 Server at api.best-office.local Port 8080</address>
`
That contains not "secured" data and it throws an exception and drop down our prod environment. It was really hard to find the root cause.

**Pull request closed without merging**
