### PR TITLE
Serialize into array

### PR DESCRIPTION
**Pull request by snapshotpl**
For me it's useful when I want to serialize messages to log using psr-4 (into context)

### CODE REVIEW

**Comment by snapshotpl** [comment]
If it ok I will make serializer for response. What are you think about deserializers from arrays?

**Comment by Ocramius** [comment]
@snapshotpl would segregate it to a separate serializer or interface (implementation can be added to existing one, but ISP must be respected IMO)

**Comment by snapshotpl** [comment]
@Ocramius as it's static method interface doesn't sense here imo.

**Comment by Ocramius** [comment]
Misread it, good point. Indeed, statics don't need interfaces.

**Comment by snapshotpl** [comment]
What about array deserializer idea?

**Comment by weierophinney** [comment]
I would create `Zend\Diactoros\Request\ArraySerializer` and `Zend\Diactoros\Response\ArraySerializer` classes, each with the methods:

- `fromArray(array $messageData)`
- `toArray(RequestInterface $request)`

The purpose of the current serializers is specifically for string de/serialization, and the methods exposed reflect that purpose. New classes specifically for array de/serialization make sense here.

**Comment by snapshotpl** [comment]
@weierophinney @Ocramius ready to review

**Comment by weierophinney** [comment]
Merged to develop for release with 1.4.0; thanks, @snapshotpl

**Pull request merged**
