### PR TITLE
Use php://temp instead of php://memory by default in Response

### PR DESCRIPTION
**Pull request by dunglas**
Avoid problem of exceeded memory when dealing with large responses.

### CODE REVIEW

**Comment by Ocramius** [comment]
@dunglas pardon the ignorance, but will `php://temp` write to memory until a limit is reached? I just want to avoid file I/O on each usage, and couldn't find clear documentation about this wrapper ;-)

**Comment by dunglas** [comment]
@Ocramius yes. The default limit is 2 Mo (can be configured by adding using a syntax like `php://temp:NN` where NN is the limit in bytes).

The doc is available here: http://php.net/manual/en/wrappers.php.php I struggled to find it too.

**Comment by Ocramius** [comment]
Thanks!

**Comment by Ocramius** [comment]
Merged, thanks!

`master`: zendframework/zend-diactoros@f347705d8debd27ba9855517d79537f0d030737b
`develop`: zendframework/zend-diactoros@0d5bc9914654f136fb8108ad1c160e9d9714128e

**Comment by sasezaki** [comment]
Title is `Response`, but changed is `Request` ?

**Comment by dunglas** [comment]
@sasezaki good catch my title is wrong. I update it.

**Pull request closed without merging**
