### PR TITLE
Bugfix: Header with value "0" is being discarded

### PR DESCRIPTION
**Pull request by malukenho**
- [x] Are you fixing a bug?

Linking #342

### CODE REVIEW

**Comment by weierophinney** [comment]
Thanks, @malukenho!

**Comment by tptrixtop** [comment]
This fix cause an issue in apache on win, because there is a header

[SERVER_SIGNATURE] =>`<address>Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.9 Server at api.best-office.local Port 8080</address>`

That contains not "secured" data and it throws an exception and drop down our prod environment. It was really hard to find the root cause.

**Comment by vakata** [comment]
This is not a proper fix - all server vars are copied as headers, which is incorrect. The problem users are reporting is when some of the server values can not be used as headers. This should probably be reverted and a simple ```strlen($val)``` check added in its place.

**Comment by froschdesign** [comment]
@vakata 
Please look #349 and add your comment there. Thanks!

**Pull request merged**
